/* Generated by Cython 0.29.22 */

#ifndef __PYX_HAVE__A3CProcesses
#define __PYX_HAVE__A3CProcesses

#include "Python.h"

#ifndef __PYX_HAVE_API__A3CProcesses

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *create_worker(float *, int, char **, int, int, int);
__PYX_EXTERN_C int *worker_infer(PyObject *, float *);
__PYX_EXTERN_C void worker_finish(PyObject *, float *);
__PYX_EXTERN_C PyObject *parameter_server_proc(float, char **, int);
__PYX_EXTERN_C void parameter_server_kill(PyObject *);

#endif /* !__PYX_HAVE_API__A3CProcesses */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initA3CProcesses(void);
#else
PyMODINIT_FUNC PyInit_A3CProcesses(void);
#endif

#endif /* !__PYX_HAVE__A3CProcesses */
